# ────────────────────────────────────────────────────────────
# Custom Theme for btop
# Made with Omarchist
# ────────────────────────────────────────────────────────────

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#5C624B"

# Title color for boxes
theme[title]="#4A0E1A"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#FF6347"

# Background color of selected item in processes box
theme[selected_bg]="#4A0E1A"

# Foreground color of selected item in processes box
theme[selected_fg]="#FF6347"

# Color of inactive/disabled text
theme[inactive_fg]="#4A4E3D"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#FF6347"

# Cpu box outline color
theme[cpu_box]="#2E2D24"

# Memory/disks box outline color
theme[mem_box]="#2E2D24"

# Net up/down box outline color
theme[net_box]="#2E2D24"

# Processes box outline color
theme[proc_box]="#2E2D24"

# Box divider line and small boxes line color
theme[div_line]="#2E2D24"

# Temperature graph colors
theme[temp_start]="#DC143C"
theme[temp_mid]="#DC143C"
theme[temp_end]="#BF0000"

# CPU graph colors
theme[cpu_start]="#DC143C"
theme[cpu_mid]="#DC143C"
theme[cpu_end]="#BF0000"

# Mem/Disk free meter
theme[free_start]="#DC143C"
theme[free_mid]="#DC143C"
theme[free_end]="#BF0000"

# Mem/Disk cached meter
theme[cached_start]="#DC143C"
theme[cached_mid]="#DC143C"
theme[cached_end]="#BF0000"

# Mem/Disk available meter
theme[available_start]="#DC143C"
theme[available_mid]="#DC143C"
theme[available_end]="#BF0000"

# Mem/Disk used meter
theme[used_start]="#DC143C"
theme[used_mid]="#DC143C"
theme[used_end]="#BF0000"

# Download graph colors
theme[download_start]="#DC143C"
theme[download_mid]="#DC143C"
theme[download_end]="#BF0000"

# Upload graph colors
theme[upload_start]="#DC143C"
theme[upload_mid]="#DC143C"
theme[upload_end]="#BF0000"
