# ────────────────────────────────────────────────────────────
# Custom Theme for Ghostty
# Made by Omarchist
# ────────────────────────────────────────────────────────────

background = #000000
foreground = #E0D4C2

cursor-color = #DC143C
cursor-text = #000000

selection-background = #2B0505
selection-foreground = #E0D4C2

# normal colors
palette = 0=#000000
palette = 1=#8B0000
palette = 2=#586259
palette = 3=#E24C00
palette = 4=#5C624B
palette = 5=#655E56
palette = 6=#7A7D80
palette = 7=#BDB5AA

# bright colors
palette = 8=#6B6867
palette = 9=#8B0000
palette = 10=#3C6A3E
palette = 11=#E24C00
palette = 12=#4A6829
palette = 13=#655E56
palette = 14=#7A7D80
palette = 15=#E0D4C2
