-- Generated by scripts/hypr2lua.
-- Source: /home/hancore/.config/omarchy/themes/demon/hyprland.conf

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(4A0E1Aee)", "rgba(0A0000ee)" },
        angle = 45,
      },
      inactive_border = "rgb(0A0000)",
    },
    border_size = 2,
    gaps_in = 3,
    gaps_out = 3,
  },
  group = {
    col = {
      border_active = {
        colors = { "rgba(4A0E1Aee)", "rgba(0A0000ee)" },
        angle = 45,
      },
      border_inactive = "rgb(0A0000)",
    },
    groupbar = {
      col = {
        active = "rgba(4A0E1A99)",
        inactive = "rgba(4D574E88)",
      },
      text_color = "rgb(DC143C)",
      text_color_inactive = "rgba(E0D4C2ff)",
    },
  },
  decoration = {
    rounding = 0,
    shadow = {
      enabled = true,
      render_power = 16,
      range = 8,
      color = "rgba(0,0,0, 0.8)",
    },
  },
})
