# ────────────────────────────────────────────────────────────
# Custom Theme for Kitty
# Made with Omarchist
# ────────────────────────────────────────────────────────────

## name: Custom Theme

foreground              #E0D4C2
background              #000000
selection_foreground    #E0D4C2
selection_background    #2B0505

cursor                  #DC143C
cursor_text_color       #000000

# URL underline color when hovering with mouse
url_color               #E0D4C2

# Tab bar colors
active_tab_foreground   #E0D4C2
active_tab_background   #121212
inactive_tab_foreground #E0D4C2
inactive_tab_background #121212
tab_bar_background      #E0D4C2

color0  #000000
color8  #6B6867
color1  #8B0000
color9  #8B0000
color2  #586259
color10 #3C6A3E
color3  #E24C00
color11 #E24C00
color4  #5C624B
color12 #4A6829
color5  #655E56
color13 #655E56
color6  #7A7D80
color14 #7A7D80
color7  #BDB5AA
color15 #E0D4C2
